### ISSUE TITLE
Error `EISDIR: illegal operation on a directory, read`

### ISSUE THREAD

**Issue by ehmicky** [Tom-Bonnike/netlify-plugin-inline-source#5]
The following error happens in some build:

```
Inlining sources failed.
EISDIR: illegal operation on a directory, read 
    fs.js:497:3 Object.readSync
    fs.js:322:20 tryReadSync
    fs.js:359:19 Object.readFileSync
    /opt/build/repo/node_modules/inline-source/lib/load.js:19:41 
    /opt/build/repo/node_modules/inline-source/lib/load.js:12:10 load
    /opt/build/repo/node_modules/inline-source/lib/run.js:17:17 
    /opt/build/repo/node_modules/inline-source/lib/run.js:14:13 run
    /opt/build/repo/node_modules/inline-source/index.js:44:15 
```

Do you know what this might be?

**Comment by Tom-Bonnike** [comment]
Do you have more info, like the file name maybe? I think this means `inline-source` is trying to read a file but it's actually a directory; I’m only passing `.html` files to `inline-source` so, that’s quite weird.

**Comment by Tom-Bonnike** [comment]
It’s probably because a link/href/src it’s trying to inline seems to be pointing to a directory instead of a file.

[This](https://github.com/popeindustries/inline-source/blob/master/lib/load.js#L19) is the line that is failing, when trying to read a “`source`” (a file that `inline-source` tries to inline), and that error means it’s trying to read a directory instead of a file.  

Is the project open-source? Do you have more info, like the file name, maybe?

**Comment by Tom-Bonnike** [comment]
Any more info on this @ehmicky? Does it happen on a lot of projects?

Would you rather I try to catch this error and stop trying to inline the file? I think letting the build fail is actually what I’d expect as a user.

**Comment by ehmicky** [comment]
No, it only happened once in that build. Unfortunately, the repository is private and the build logs are not giving out additional information.

**Comment by Tom-Bonnike** [comment]
OK. I’ll close for now, happy to re-open if you start seeing it on more projects.
